### ISSUE TITLE
Crash due to  NSInvalidArgumentException in sdl_registerResponse

### ISSUE THREAD

**Issue by ashwink11** [smartdevicelink/sdl_ios#1173] opened 2019-03-05 10:37 UTC
### Bug Report
NSInvalidArgumentException in sdl_registerResponse

##### Reproduction Steps
Crash report received from released app, no known steps.

##### Expected Behavior
App should not crash

##### OS & Version Information
* OS Version: 12.1.4 (16D57)
* Device: iPhone X
* SDL iOS Version: 6.1.2
* Testing Against: [What you tested with to observe this behavior]

##### Test Case, Sample Code, and / or Example App
[issue_689_crash.txt](https://github.com/smartdevicelink/sdl_ios/files/2930542/issue_689_crash.txt)

**Comment by joeljfischer** [comment] 2019-03-15 18:35
Duplicate of #1159 / #1153

**Closed by joeljfischer** 2019-03-15 18:35 UTC
Labels: bug
