### ISSUE TITLE
Crash on SDL start after calling and force close (WebEx)

### ISSUE THREAD

**Issue by standa1-ford** [smartdevicelink/sdl_ios#1825] opened 2020-10-21 07:36 UTC
### Bug Report
When iPhone 11 Pro connects to the HU, a phantom call appears on the HU and result in SDL crash

##### Reproduction Steps
Connect phone to HU via BT
Notice phone call on the HU.
Press End Call button on HU and notice that the phone call disconnects.
Now, on the phone launch WebEx.
Notice phone call on the HU again.
On the phone, swipe up in the recent apps tray and force close WebEx.
Notice on HU, WebEx gets unregistered and the phone call is ended automatically.
Turn BT OFF and then back ON on HU.
Notice WebEx appears and then disappears on HU (WebEx crashes).

##### Expected Behavior
App should not crash

##### Observed Behavior
App crashes

##### OS & Version Information
* iOS Version: iPhone 11 Pro Only (iOS 14)
* Testing Against: Sync 3.2v2 via BT

##### Test Case, Sample Code, and / or Example App
Attached is stack trace of the crash
[phantom-caller.log](https://github.com/smartdevicelink/sdl_ios/files/5414068/phantom-caller.log)

**Comment by FrankElias77** [comment] 2020-10-27 13:16
Hello, did you use a USB cord to register your app ?

**Comment by joeljfischer** [comment] 2020-10-27 15:50
Hi @standa1-ford, this seems to be a duplicate of https://github.com/smartdevicelink/sdl_ios/issues/1811, which was closed.

I performed the reproduction step of connecting an example app on an iPhone 11 Pro to a Sync 3.4 head unit and no "phantom call" appeared. Are you certain that your reproduction steps are correct? Have you attempted this with an example app? Do you have symbolicated logs?

**Comment by stefanek22** [comment] 2020-10-27 22:10
Make sure to go into the Webex app settings and choose Devices >> Discover Devices (ON) ... this seems to induce the phantom call on the IVI head unit (that leads to the subsequent issue)

**Comment by joeljfischer** [comment] 2020-10-28 17:21
@stefanek22 This bug report doesn't mention Webex (`When iPhone 11 Pro connects to the HU, a phantom call appears on the HU and result in SDL crash`). I think that the bug report and reproduction steps need to be fixed and a symbolicated log is necessary or this bug cannot be investigated properly.

**Comment by standa1-ford** [comment] 2020-11-03 09:41
hi @joeljfischer I've updated the reproduction steps as follows.  Also the attached crash log is specific to the Webex app.

Connect phone to HU via BT
Notice phone call on the HU.
Press End Call button on HU and notice that the phone call disconnects.
Now, on the phone launch WebEx.
Notice phone call on the HU again.
On the phone, swipe up in the recent apps tray and force close WebEx.
Notice on HU, WebEx gets unregistered and the phone call is ended automatically.
Turn BT OFF and then back ON on HU.
Notice WebEx appears and then disappears on HU (WebEx crashes).

**Comment by joeljfischer** [comment] 2020-11-05 17:58
Hi @standa1-ford, as it is, this is still an impossible bug to fix because the log provided is not symbolicated and the reproduction steps require a closed source app. Either an open-source app / reproduction steps are necessary, or at least a symbolicated crash log (and that may not be enough, but it's at least a start). Until that is provided, nothing can be done on this issue.

**Comment by joeljfischer** [comment] 2021-03-04 14:28
Hi @standa1-ford, I'm closing this issue due to inactivity. It can be reopened if needed!

**Closed** 2021-03-04 14:28 UTC
Labels: bug
