### ISSUE TITLE
App shutting down on Out-of-memory error when video streaming is started about 10 minutes if the WiFi signal is extremely weak.

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_ios#1529] opened 2020-01-28 01:42 UTC
### Bug Report
App shutting down on Out-of-memory error when video streaming is started about 10 minutes if the WiFi signal is extremely weak.

##### Preconditions
The WiFi signal is extremely weak.

##### Reproduction Steps
1. Connect the head unit to the phone via BT+WiFi
2. Register a NaviAPP
3. Activate a NaviAPP
4. Start video streaming
5. After about 10 minutes

##### Expected Behavior
App not shutting down on Out-of-memory error

##### Observed Behavior
App shutting down on Out-of-memory error

①The data of video streaming is saved into `SDLTcpTransport's sendDataQueue`,
then is sent to HU.

```
#pragma mark - Data Transmission

- (void)sendData:(NSData *)msgBytes {
    [self.sendDataQueue enqueueBuffer:msgBytes.mutableCopy];

    [self performSelector:@selector(sdl_writeToStream) onThread:self.ioThread withObject:nil waitUntilDone:NO];
}

- (void)sdl_writeToStream {
    NSAssert([[NSThread currentThread] isEqual:self.ioThread], @"sdl_writeToStream is called on a wrong thread!");

    if (!self.outputStreamHasSpace || [self.sendDataQueue count] == 0) {
        return;
    }

    NSMutableData *buffer = [self.sendDataQueue frontBuffer];
    NSUInteger bufferLen = buffer.length;

    NSInteger bytesWritten = [self.outputStream write:buffer.bytes maxLength:bufferLen];
    if (bytesWritten < 0) {
        SDLLogW(@"TCP transport write error: %@", self.outputStream.streamError);
        [self sdl_onStreamError:self.outputStream];
        return;
    } else if (bytesWritten == 0) {
        SDLLogD(@"TCP transport output stream closed");
        [self sdl_onStreamEnd:self.outputStream];
        return;
    }

    if (bytesWritten == bufferLen) {
        // we have consumed all of data in this buffer
        [self.sendDataQueue popBuffer];
    } else {
        [buffer replaceBytesInRange:NSMakeRange(0, (NSUInteger)bytesWritten) withBytes:NULL length:0];
    }

    // the output stream may still have some spaces, but let's wait for another NSStreamEventHasSpaceAvailable event before writing
    self.outputStreamHasSpace = NO;
}
```

②There is no limit to the size of the `sendDataQueue`，so the app can save streaming data into the queue without limit.
packetQueue' data can't be sent to HU via TCP immediately when the WiFi signal is extremely weak, so Out-of-memory error occurs.

##### OS & Version Information
* iOS Version: 10.2
* SDL iOS Version: 6.4.1
* Testing Against: SDL Core 6.0.1 + HMI running on our development environment.

##### Occurrence
100%

##### Recovery Method:
Kill the NaviAPP, connect BT+WIFI, restart the NaviAPP

**Comment by lapinskijw** [comment] 2020-03-04 14:36
Hi @zhouxin627, could you provide additional information on how to reproduce this issue? Any details you could provide regarding weak WiFi and how you simulated it would be helpful as well. Thanks!

**Comment by zhouxin627** [comment] 2020-03-05 07:03
Hi @lapinskijw, there are two ways to simulate it:
1. Increase the distance from WiFi AP to reduce the signal strength of the WiFi connection.
2. Send a large number of `audiostreaming` data continuously to occupy WiFi bandwidth

As long as the data can not be sent out in time, data accumulation occurs.

**Comment by theresalech** [comment] 2020-04-01 15:14
During the 2020-03-31 Steering Committee meeting, the committee voted to close this issue as "won't fix." This is because the issue is seen as a rare corner case, unlikely to be encountered in production, and a potential fix would increase technical debt in comparison with the likelihood of the issue.

**Closed by theresalech** 2020-04-01 15:14 UTC
Labels: bug, transport-secondary
