### ISSUE TITLE
SDLShowConstantTBT doesn't seem to attempt a PutFile within the first minute or 2 of connecting to SYNC/CTR

### ISSUE THREAD

**Issue by MichaelCrimando** [smartdevicelink/sdl_ios#1138] opened 2018-12-13 13:47 UTC
### Bug Report
SDLShowConstantTBT doesn't seem to attempt a PutFile within the first minute or 2 of connecting to SYNC/CTR

##### Reproduction Steps
1. Before connecting to the headunit, use a mobile nav app (like Antelope iOS or Waze), to start a route and get on the route. (So the app doesn't say "Proceed to highlighted route")
2. Connect phone to TDK and launch it on SYNC
3. If using Waze or Antelope iOS 4.3+, go to some other domain so that the app is in LIMITED. In this state, the apps will send showConstantTBTs

##### Expected Behavior
SDL Library does a PutFile with the requested image, does the showConstantTBT RPC and then does the alertManeuver so that the TBT directions are shown on the display.

##### Observed Behavior
The SDL Library doesn't seem to do a PutFile, so it requests a showConstantTBT with an image that doesn't exist.  SYNC and CTR respond with an INVALID_DATA to the showConstantTBT RPC.

Issue seems to heal itself after a minute or 2, where the library will start sending the putFile again

##### OS & Version Information
* iOS Version: 12.1
* SDL iOS Version: 6.1.2
* Testing Against: 
On 10"L (Navigator screen) SYNC TDK with NA NAV software
or CTR version GP510
Waze 4.46.0
Antelope iOS V4.2

##### Test Case, Sample Code, and / or Example App
```
let sdlTurnImage = SDLImage(name: visualFileName, ofType: .dynamic, isTemplate: false)
let newTBT = SDLShowConstantTBT(navigationText1: navText1, navigationText2: distanceString, eta: nil, timeToDestination: nil, totalDistance: nil, turnIcon: sdlTurnImage, nextTurnIcon: nil, distanceToManeuver: distanceToManuever, distanceToManeuverScale: distanceToManeuverScale, maneuverComplete: false, softButtons: nil)
ProxyManager.sharedManager.sdlManager.send(request: newTBT, responseHandler: {[weak self]
...
```

**Comment by MichaelCrimando** [comment] 2018-12-13 13:52
Sync Logs:
[SYNC BF2 RC Logs.zip](https://github.com/smartdevicelink/sdl_ios/files/2676264/SYNC.BF2.RC.Logs.zip)

The CTR logs need special tools to analyze, but here's the snipped the team gave me
1.Device got connected
45952 2018/12/07 13:37:02.000000 95.3544 156 ECU1 ALCO JOUR 1277 log debug verbose 1 SDLCore_4.2.091517.5022572 [1422]:[CUsbEapDeviceScanner.cpp:304] :handleUSBDevice::Device Status 1
 
2.Received graphic image 5.png, with persistency false.
95875 2018/12/07 13:37:26.000000 119.5313 16 ECU1 ALCO JOUR 1277 log info verbose 1 SDLCore_4.2.091517.5022572 [1394]:[mobile_message_handler.cc:106] :HandleIncomingMessageProtocol::Incoming RPC_INFO: 1, Request, 32, 22, {"fileType":"GRAPHIC_PNG","length":3617,"syncFileName":"5.png","persistentFile":false,"offset":0}
 
3.Disconnected the Device
137606 2018/12/07 13:37:52.000000 145.5097 140 ECU1 ALCO JOUR 1277 log debug verbose 1 SDLCore_4.2.091517.5022572 [1422]:[CUsbEapDeviceScanner.cpp:304] :handleUSBDevice::Device Status 0
 
4.As turn icon is non-persitency file, it's removed from storage folder with device disconnection.
137774 2018/12/07 13:37:52.000000 145.6156 255 ECU1 ALCO JOUR 1277 log info verbose 1 SDLCore_4.2.091517.5022572 [1393]:[application_impl.cc:896] :CleanupFiles::DeleteFile file /mnt/data/applink/storage/2626965156_89ede94fc564387ba73994b14b11435425fe3109a59f6f8776a1fef3bc64c67e/5.png
 
5.Re-Connected the Device
145213 2018/12/07 13:38:08.000000 161.3897 136 ECU1 ALCO JOUR 1277 log debug verbose 1 SDLCore_4.2.091517.5022572 [1422]:[CUsbEapDeviceScanner.cpp:304] :handleUSBDevice::Device Status 1
 
6.Received ShowConstantTBT request from Mobile app. But HU doesn't have reference for 5.png. Request rejected with reponse INVALID_DATA.
226915 2018/12/07 13:39:02.000000 215.9558 118 ECU1 ALCO JOUR 1277 log info verbose 1 SDLCore_4.2.091517.5022572 [1394]:[mobile_message_handler.cc:106] :HandleIncomingMessageProtocol::Incoming RPC_INFO: 1, Request, 27, 13, {"navigationText1":"Turn Slight Left:","navigationText2":"1.0mi","distanceToManeuver":1624,"distanceToManeuverScale":1624,"turnIcon":{"value":"5.png","imageType":"DYNAMIC"},"maneuverComplete":false}
226964 2018/12/07 13:39:02.000000 215.9676 163 ECU1 ALCO JOUR 1277 log info verbose 1 SDLCore_4.2.091517.5022572 [1400]:[mobile_message_handler.cc:131] :HandleOutgoingMessageProtocol::Outgoing RPC_INFO: 1, Response, 27, 13, { "resultCode" : "INVALID_DATA", "success" : false }

**Comment by joeljfischer** [comment] 2019-08-12 18:55
@MichaelCrimando Is this reproducible on the develop branch? We've done a lot of work on threading and queueing to make the library quicker.

A few additional notes:

1. This is very difficult to reproduce without a sample project.
2. It appears that you're trying to send a file with `PutFile` and then show the image using `SDLImage`. I'd recommend doing so with `SDLFileManager` instead, because it'll give you a callback block when the file has finished uploading, and so you can measure how long it's taking. You will also be able to see what other RPCs and uploads are occurring.
3. The most likely cause of this is due to (a) a large number of RPCs or video data are "blocking up" the pipe to upload your image, or (b) the head unit is not responding due to a large number of RPCs coming in at once. Sync 3 appears to be badly susceptible to this kind of behavior in our experience.

**Comment by joeljfischer** [comment] 2019-09-10 20:27
Closing due to inactivity

**Comment by MichaelCrimando** [comment] 2019-09-20 18:39
@NicoleYarroch @joeljfischer 
Just retested this and it still occurs. How can I best help get this fixed?
iPhone 6S
iOS 12.4.1
Antelope Test App v4.6 with SDL iOS v6.3.1
SYNC version 3.4.19248

**Comment by joeljfischer** [comment] 2019-09-20 19:07
@MichaelCrimando Have you looked at my notes in my comment from August 12th?

**Comment by MichaelCrimando** [comment] 2019-09-20 19:15
@joelfischer I don't have my Mac today but I can have a more in depth look next week. Do you need a sample project? You can test this with Waze

**Comment by joeljfischer** [comment] 2019-09-20 19:19
We'd need to see the logs on iOS to be able to determine if it's an iOS library issue or an issue with Sync, so a released app like Waze won't work.

**Comment by MichaelCrimando** [comment] 2019-10-14 20:31
Ok @joeljfischer finally got logs
[Logs.zip](https://github.com/smartdevicelink/sdl_ios/files/3726313/Logs.zip)

iOS 13.1.2
iPhone 6s
Antelope test app v4.7
SDL Library v6.3.1
SYNC version 3.4.19248

**Comment by joeljfischer** [comment] 2020-02-18 18:09
@MichaelCrimando Unfortunately, as I noted before, this still isn't enough. Have you performed the steps noted [above](https://github.com/smartdevicelink/sdl_ios/issues/1138#issuecomment-520551434)? Additionally, mere logs aren't enough here. As I said, there needs to be a sample app that can be built using Xcode so that we can use debug tools.

**Comment by MichaelCrimando** [comment] 2020-02-18 21:44
@joeljfischer 
Lol I was just thinking about this issue the other day.  I will sya that I don't care enough about it to make a sample app to trouble shoot it. So there's that

**Comment by joeljfischer** [comment] 2020-02-18 21:49
Okay, I'll close this issue for now. If it ever comes up in a reproducible way with testable code, we can reopen it.

**Closed by joeljfischer** 2020-02-18 21:49 UTC
Labels: bug
