### ISSUE TITLE
Video stream started notification not sent

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1481] opened 2019-12-02 13:26 UTC
### Bug Report
Has anyone tried iOS SDK 6.4.1 with SDL Core 4.5? When testing with the streaming app, the app is able to connects to the SDL core, and recongnized by SDL Core.
But when ActivateApp is sent from the SDL Core, the iOS SDK didn't send `SDLVideoStreamDidStartNotification` notification to the app at all. only SDL lock screen appears.
It works fine when rollback the SDK to 6.3.1.

##### OS & Version Information
* iOS Version: X.X.X
* SDL iOS Version: 6.4.1
* Testing Against: SDL Core 4.5

**Comment by NicoleYarroch** [comment] 2019-12-03 18:55
I could not reproduce this issue.

Tested with:
* SDL iOS version 6.4.1
* [SDL Core](https://github.com/smartdevicelink/sdl_core) version 4.5.2 
    * (commit 29f009648977bf73cce52148ff63c761c028eac9 (HEAD -> branch_4.5.2, tag: 4.5.2, origin/release/4.5.2))
* [SDL HMI](https://github.com/smartdevicelink/sdl_hmi) version 5.2.0
    * (commit bd53f11339ee4d95a41caf5e5edf4ae0839d5957 (HEAD -> develop, origin/develop))

The only thing I can think might be happening is that the app on the device might be backgrounded or the SDL app's `hmiLevel` is not `FULL`. The device app must be in the foreground and the SDL app must be open in order for video streaming to work. 

If you can still reproduce the issue, please leave detailed information about the HMI, Core and phone being used.

**Comment by ed-h** [comment] 2019-12-09 10:01
@NicoleYarroch 

Yes, I still can reproduce the issue.  the device app is in foreground when testing. The weird thing that this only happens on debug build. If its release build, the ProxyManager can receive SDLVideoStreamDidStartNotification.

I have noticed that in the debug build, SDLStreamingVideoLifecycleManager.m,  function sdl_startVideoSession
it will enter following block

>  if (!self.isStreamingSupported) {
        SDLLogV(@"Streaming is not supported. Video start service request will not be sent.");
        return;
    }

(The same app code has no issue with 6.3.x in either release/debug build.)

**Comment by joeljfischer** [comment] 2019-12-09 16:23
@ed-h Which module (head unit) are you testing with?

**Comment by ed-h** [comment] 2019-12-10 01:15
@joeljfischer  Its a head unit developed by ourselves that is based on SDL Core 4.5.2.

**Comment by joeljfischer** [comment] 2019-12-10 14:23
@ed-h The issue appears to be that your head unit is not setting `registerAppInterfaceResponse.hmiCapabilities.videoStreaming` to `true`. Therefore, your head unit is declaring that it does not support video streaming.

**Comment by ed-h** [comment] 2019-12-18 04:09
After further debugging,  I have found that displayType is **NSNull** in both 6.4.1 debug/release, and 6.3.1 debug/release when connecting to our Head Unit running SDL Core 4.5.2

However only 6.4.1 has an additional function call 
`    self.displays = [self sdl_createDisplayCapabilityListFromRegisterResponse:response];
`

and there will be an **SDLLogAssert** in NSMutableDictionary+Store.m with the following line since displayType is null

`    NSString *displayName = display.displayName ?: display.displayType;
`

It seems that if the Head Unit has the displayType set to **SDL_GENERIC**, SDK will have a null value of displayType. If I change the displayType to **GEN2_8_DMA**, the displayType will be correct in iOS SDK.


It looks like SDL Core 4.5.2 is missing the following line in **hmi_capabilities_impl.cc**
`display_type_enum.insert(std::make_pair(
      std::string("SDL_GENERIC"), hmi_apis::Common_DisplayType::SDL_GENERIC));
`

**Comment by joeljfischer** [comment] 2019-12-18 13:57
It sounds like your head unit is returning `NULL` as a value in the `RIAR.displayType` JSON, which should not occur.

@JackLivio This sounds like a bug in SDL Core 4.5.2? If so, what would you recommend as a fix? Should they try to patch their version of Core?

cc @joeygrover

**Comment by chinlin0924** [comment] 2019-12-31 14:51
I think the change can be backported to older core, so that the newer SDK can work for different SDL-core.

https://github.com/smartdevicelink/sdl_core/blob/4d283e625dfa09d166d572fa7bf6e98e91f05050/src/components/application_manager/src/hmi_capabilities_impl.cc#L381

**Comment by theresalech** [comment] 2020-01-13 14:48
@chinlin0924 can you please provide an update on your status?

**Comment by joeljfischer** [comment] 2020-01-21 18:49
Closing as not an sdl_ios bug

**Closed by joeljfischer** 2020-01-21 18:49 UTC
Labels: bug
