### ISSUE TITLE
Computed properties should not be retained using object association

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_ios#69] opened 2015-02-05 20:11 UTC
Especially in the case of the [putFileRPCRequest](https://github.com/smartdevicelink/SmartDeviceLink-iOS/blob/master/sdl_ios/SmartDeviceLink/SDLProxy.m#L528), which is already retained as an object association by the inputStream.

The only time this property is retrieved is in the proxy's [[stream:handleEvent]](https://github.com/smartdevicelink/SmartDeviceLink-iOS/blob/master/sdl_ios/SmartDeviceLink/SDLProxy.m#L534-582) method, which has access to the [putFileRPCRequest](https://github.com/smartdevicelink/SmartDeviceLink-iOS/blob/master/sdl_ios/SmartDeviceLink/SDLProxy.m#L553) which computes the property.

**Comment by joeljfischer** [comment] 2016-01-20 16:07
Duplicate of #223

**Closed by joeljfischer** 2016-01-20 16:07 UTC
Labels: best practice
