### ISSUE TITLE
Sync4 USB connect iphone, App supported CallKit forced jump from SDL UI to CarPlay. 

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#2070] opened 2022-01-19 10:26 UTC
### Bug Report
1. Using USB connect iphone to TDK, and TDK not enabled carplay.
2. Start an App using audio with callkit support.
3. From SDL UI forced jump to carplay UI. 
4. If using BlueTooth connect iphone no this issue.

##### Reproduction Steps
1. Using USB connect iphone to TDK, and TDK not enabled carplay.
2. Start an App using audio with callkit support.
3. From SDL UI forced jump to carplay UI. 
4. If using BlueTooth connect iphone no this issue.

##### Expected Behavior
Keeps in SDL UI, not auto jump to CarPlay.

##### OS & Version Information
* iOS Version: [Any]
* SDL iOS Version: [Sync4]

**Comment by joeljfischer** [comment] 2022-01-19 14:29
Hello @84798012, from reading this bug this appears to be a TDK issue. Have you talked to Ford about the issue? Unless you have additional logs or evidence that this issue is caused by, or can be fixed by, the SDL iOS library, I will close this issue.

**Comment by 84798012** [comment] 2022-01-20 02:56
@joeljfischer  Thanks for you feedback. I'll connect with Ford to check if this is Ford TDK issue.

**Closed** 2022-01-26 20:03 UTC
