### ISSUE TITLE
Sending an SDLPerformAudioPassThru request does not call the completion handler

### ISSUE THREAD

**Issue by zeusent** [smartdevicelink/sdl_ios#1497] opened 2019-12-10 12:55 UTC
### Bug Report
I'm trying to perform an SDLPerformAudioPassThru request. Everything seems to work fine. The popup shows up in the head unit and the recording starts. The `audioDataHandler` is being fired on my iOS device with chunks of audio data *but* the completion handler for the `send` command is never fired when the recording is ended no matter what the way of ending is.

Here's my piece of code:

##### Test Case, Sample Code, and / or Example App
```
let maxDuration: UInt32 = 10000
let audioPassThruRequest = SDLPerformAudioPassThru(initialPrompt: "Speak your note now", audioPassThruDisplayText1: "Recording...", audioPassThruDisplayText2: nil, samplingRate: .rate16KHZ, bitsPerSample: .sample16Bit, audioType: .PCM, maxDuration: maxDuration, muteAudio: true, audioDataHandler: { [weak self] (newData) in
    print("Got new audio data... Appending it to existing one")
    self?.audioData = (self?.audioData ?? Data()) + (newData ?? Data())
})

sdlManager.send(request: audioPassThruRequest) { [weak self] (request, response, error) in
    // This callback is never fired!
}

```

**Comment by NicoleYarroch** [comment] 2019-12-10 13:28
@zeusent Can you give us more information about the version of SDL iOS you are using and the head unit or emulator (type and version) you are using?

**Comment by zeusent** [comment] 2019-12-10 13:31
Of course. Sorry for missing those. I'm using SDL for iOS version 6.4.1 (installed it via Cocoapods) and I'm testing using a Development Kit TDK-x2.1 U2.1-245

**Comment by NicoleYarroch** [comment] 2019-12-10 14:02
@zeusent Assuming that is a Ford TDK, can you go to **Settings > General > About SYNC** and tell me the version number shown there.

**Comment by zeusent** [comment] 2019-12-10 14:06
Here you go:

![BB2EA5E6-8727-404E-8735-8EB8B09A908D](https://user-images.githubusercontent.com/777591/70536207-98a44680-1b5e-11ea-90bf-e9d00ca51f30.jpeg)
![0E0961F1-9276-45F1-B8D6-D75E9B6D3E50](https://user-images.githubusercontent.com/777591/70536208-98a44680-1b5e-11ea-88c1-96a619cf2039.jpeg)

**Comment by zeusent** [comment] 2019-12-10 15:37
Ok... If I define my completion handler as an instance variable everything seems to be fine. So maybe somehow the handler gets deallocated whenever it's passed inline?

So my code looks something like this now:

```
func startRecording() {
    let maxDuration: UInt32 = 10000
    let audioPassThruRequest = SDLPerformAudioPassThru(initialPrompt: "Speak your note now", audioPassThruDisplayText1: "Recording...", audioPassThruDisplayText2: nil, samplingRate: .rate16KHZ, bitsPerSample: .sample16Bit, audioType: .PCM, maxDuration: maxDuration, muteAudio: true, audioDataHandler: { [weak self] (newData) in
        print("Got new audio data... Appending it to existing one")
        self?.audioData = (self?.audioData ?? Data()) + (newData ?? Data())
    })
    
    sdlManager.send(request: audioPassThruRequest, responseHandler: completionHandler)
}

var completionHandler = { (request, response, error) in
    // This callback IS fired!
}
```

**Comment by NicoleYarroch** [comment] 2019-12-10 15:48
I would recommend looking at the `PerformAudioPassThru`  example in the Swift example app: https://github.com/smartdevicelink/sdl_ios/blob/master/Example%20Apps/Example%20Swift/AudioManager.swift

**Comment by NicoleYarroch** [comment] 2019-12-10 15:49
Closing since this is an implementation issue and not a library bug.

**Comment by zeusent** [comment] 2019-12-10 16:11
I must disagree :P This is a BUG.

There is no requirement in the Swift language to declare your blocks as an instance variable and to retain them before passing them to some method. And there's no such mention in the documentation of the SDL either. The SDL should make sure it retains the handler no matter how it's passed by an a developer implementing the SDK.

Anyway, thanks for your feedback!

**Comment by joeljfischer** [comment] 2019-12-10 16:20
@zeusent We will do additional investigation into this issue. We haven't encountered it before and the swift example project doesn't suffer from it as far as I'm aware.

**Comment by joeljfischer** [comment] 2019-12-11 15:50
I've done further investigation and I'm not seeing this issue. Here is my code, which I added in the example swift app MenuManager.swift:

```swift
class func menuCellAudioPassThru(with manager: SDLManager) -> SDLMenuCell {
    return SDLMenuCell(title: "Audio Pass Thru", icon: nil, voiceCommands: nil) { (_) in
        let audioPassThru = SDLPerformAudioPassThru(initialPrompt: "Say somethin", audioPassThruDisplayText1: "This is a test", audioPassThruDisplayText2: "Stealin your voice", samplingRate: .rate16KHZ, bitsPerSample: .sample16Bit, audioType: .PCM, maxDuration: 10000, muteAudio: true) { (data) in
            print("Received audio data")
        }

        manager.send(request: audioPassThru) { (req, res, err) in
            print("Audio pass thru response: \(res)")
        }
    }
}
```

This results in the logs:

```
Received audio data
Received audio data
Received audio data
Received audio data
Received audio data
Received audio data
Audio pass thru response: Optional(PerformAudioPassThru (response), id: 81
{
    resultCode = SUCCESS;
    success = 1;
})
```

**Comment by joeljfischer** [comment] 2019-12-11 15:54
Is your `self` perhaps going to `nil`? Could you provide a sample project that reproduces your issue?

**Comment by zeusent** [comment] 2019-12-11 15:54
Thanks @joeljfischer ! I have a really small example app that I was fooling around with. So I'll try to upload it somewhere so you can take a look.

**Comment by joeljfischer** [comment] 2020-01-13 14:33
Closing for inactivity

**Closed by joeljfischer** 2020-01-13 14:33 UTC
Labels: bug
