### ISSUE TITLE
IAP-BT to IAP-USB causes [Lifecycle] Failed to register the app

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#1079] opened 2018-09-19 22:13 UTC
[HelloSDLBT2USBConsole.log](https://github.com/smartdevicelink/sdl_ios/files/2658521/HelloSDLBT2USBConsole.log)
### Bug Report
Connecting device from IAP-BT to IAP-USB causes manager to stop registering to HU

##### Reproduction Steps
Ensure you have SDL enabled App on Phone.
Pair and connect iPhone over BT to Sync 3.2v2
App should register on SYNC
Now, connect the same device via USB to SYNC
(Internally, when the device connects over USB the device and SYNC setups another iAP session over USB. Once SYNC can determine that it is the same device which is connected over BT and USB, SYNC will proceed to disconnect the iAP session over BT)
Note the messages received on App (SDL disconnects, doesn't appear on head unit)
 
##### Expected Behavior
App should un-register since they were connected over BT and then immediately re-register over USB

##### Observed Behavior
App unregisters and then disconnects the manager completely over USB

##### OS & Version Information
* iOS Version: iOS 11, iOS 12
* SDL iOS Version: 6.0.1
* Testing Against: SYNC 3.2v2

**Comment by joeljfischer** [comment] 2018-11-29 19:03
@SatbirTanda See if this PR (released in v6.1.2) fixes your issue https://github.com/smartdevicelink/sdl_ios/pull/1114

**Comment by SatbirTanda** [comment] 2018-12-07 19:20
Hey Joel - after testing with 6.1.2 it looks like the issue persists

**Comment by NicoleYarroch** [comment] 2019-01-17 21:20
I was able to reproduce on iOS 12.12 (iPhone XS Max). I suspect the issue is occurring because the stream delegates for the `EAAccessory` are not being set to `nil` when the `EAAccessory` disconnects. I will create a PR to fix this issue.

**Comment by NicoleYarroch** [comment] 2019-02-05 15:54
@SatbirTanda Can you check [PR 1150](https://github.com/smartdevicelink/sdl_ios/pull/1150) and see if it fixes your issue?

**Comment by standa1-ford** [comment] 2019-02-18 21:26
@NicoleYarroch Hey Nicole, After doing some testing (connecting iPhone 7 to SYNC 3.2v2 via BT and then USB several) I can confirm that the I see the app appearing successfully via the fix in that PR

**Comment by SatbirTanda** [comment] 2019-02-18 21:27
@NicoleYarroch Hey Nicole, After doing some testing (connecting iPhone 7 to SYNC 3.2v2 via BT and then USB several) I can confirm that the I see the app appearing successfully via the fix in that PR

**Comment by NicoleYarroch** [comment] 2019-03-06 16:53
Fixed in PR #1150

**Closed by NicoleYarroch** 2019-03-06 16:53 UTC
Labels: bug
