### ISSUE TITLE
SDLLockScreenPresenter overrides native app's supportedInterfaceOrientations and shouldAutorotate properties 

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#1250] opened 2019-04-26 01:24 UTC
### Bug Report
If a developer wants to create an app that supports both portrait and landscape orientation for some (not all) of their view controllers (with SDL integrated), then they should expect their portrait only view controllers to stay the same even if the device is rotated.  When `SDLLockScreenPresenter` is initialized, it creates a new `UIWindow` object that, for some reason, alters the properties of view controllers in other`UIWindow` objects in the app to match that of it's `rootViewController` - including those view controllers that are in the native app's `UIWindow` object.  This results in the status bar auto-rotating to conform to `SDLScreenshotViewController`'s `supportedInterfaceOrientations` and `shouldAutorotate` properties.

##### Reproduction Steps
1. Set the UIViewControllerBasedStatusBarAppearance property to YES in Info.plist of the app
```xml	
        <key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
```
2. Make sure your app supports Landscape left, landscape right, portrait (can be done in Target or Info.plist)
3. Now, you should be able to choose (through your code) which view controllers will support which orientations.
4.  Thus if one view controller only wanted to support portrait, then override supportedInterfaceOrientations to return .portrait 
5.  Create an `SDLManager` object and call its `start` method (in AppDelegate).
6.  Use app and rotate the device to landscape - you will see the status bar rotate even though the view controller supports portrait only

##### Expected Behavior
View controllers that only support the portrait orientation should not see the status bar rotate when the device rotates

##### Observed Behavior
View controllers that only support the portrait orientation do see the status bar rotate when the device rotates

##### OS & Version Information
* iOS Version: 12.2
* SDL iOS Version: 6.2.0
* Testing Against: There is no need to connect the iOS device to a Head Unit

##### Test Case, Sample Code, and / or Example App
I've attached two example apps that display the bug, one that initializes its AppDelegate's window property in code, and the other that initializes via Storyboards.
[StatusBarBug-Nibs.zip](https://github.com/smartdevicelink/sdl_ios/files/3119370/StatusBarBug-Nibs.zip)
[StatusBarBug-StoryBoard.zip](https://github.com/smartdevicelink/sdl_ios/files/3119371/StatusBarBug-StoryBoard.zip)

**Comment by SatbirTanda** [comment] 2019-04-26 01:27
In order to make sure the `SDLScreenshotViewController` doesn't override the properties of other view controllers, this code added to the class helps it conform to the native app's preferences

```objc
- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    UIViewController *viewController = [UIApplication sharedApplication].windows[0].rootViewController;
    
    if (viewController) {
        return viewController.supportedInterfaceOrientations;
    }
    
    return super.supportedInterfaceOrientations;
}
 
- (BOOL)shouldAutorotate {
    UIViewController *viewController = [UIApplication sharedApplication].windows[0].rootViewController;
    
    if (viewController) {
        return viewController.shouldAutorotate;
    }
    
    return super.shouldAutorotate;
}
```

**Comment by SatbirTanda** [comment] 2019-05-01 23:04
Also, an interesting note in th Apple docs: https://developer.apple.com/documentation/uikit/uiviewcontroller/1621435-supportedinterfaceorientations?language=objc and 

`When the user changes the device orientation, the system calls this method on the root view controller or the topmost presented view controller that fills the window. If the view controller supports the new orientation, the window and view controller are rotated to the new orientation. This method is only called if the view controller's shouldAutorotate method returns YES.`

**Comment by joeljfischer** [comment] 2019-05-02 14:33
I don't think the code you gave will work in all cases. For example, if the root view controller is a `UINavigationViewController` or `UITabViewController` and only some of the presented views support autorotation, or if a modal view controller is presented and it doesn't support autorotation.

**Comment by joeljfischer** [comment] 2019-05-02 15:14
@SatbirTanda please check my PR #1252. Thank you for the detailed issue, reproduction steps, example projects, etc. It made fixing this bug much easier and faster!

**Comment by joeljfischer** [comment] 2019-05-02 15:17
[StatusBar 3.zip](https://github.com/smartdevicelink/sdl_ios/files/3138699/StatusBar.3.zip)

Attached is an example project showing the fix including a fix for presented view controllers, which I did confirm was not fixed by the code given above. We have to traverse the root view controller to check for modally presented views and use their autorotation preferences if they exist.

Note that we do _not_ need to check the navigation controller or tab bar controller because the autorotation preferences don't cascade that way. If they want to offer different autorotation preferences per tab bar tab or navigation controller child controller, they must do something to return the child controller's rotation preferences within the container controller. As such, we don't traverse those containers for their children.

**Comment by joeljfischer** [comment] 2019-05-02 15:45
[StatusBar 3.zip](https://github.com/smartdevicelink/sdl_ios/files/3138835/StatusBar.3.zip)

**Closed** 2019-05-08 14:24 UTC
Labels: bug
