### ISSUE TITLE
Crash on EAOutputStream close

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#1583] opened 2020-03-11 20:30 UTC
### Bug Report
App crashes on EAOutputStream close

##### Reproduction Steps
Unknown

##### Expected Behavior
Does not crash 

##### Observed Behavior
Crash

##### OS & Version Information
* iOS Version: iOS 13.3.1
* SDL iOS Version: 6.5.0
* Testing Against: Unknown

##### Test Case, Sample Code, and / or Example App
Attached are 3 crash log
[2020-03-07_16-33-19.1177_-0800-56f13d5b17a6798f17cc510ad61b983cd92fef5d.txt](https://github.com/smartdevicelink/sdl_ios/files/4320743/2020-03-07_16-33-19.1177_-0800-56f13d5b17a6798f17cc510ad61b983cd92fef5d.txt)
[2020-03-07_22-05-49.2589_-0500-a752a3d0f896ed979b8fff1ebb86ac7459d817cb.txt](https://github.com/smartdevicelink/sdl_ios/files/4320744/2020-03-07_22-05-49.2589_-0500-a752a3d0f896ed979b8fff1ebb86ac7459d817cb.txt)
[2020-03-08_10-57-02.3686_-0600-f66ff644537c9aa2d0c57075a620d170f4875867.txt](https://github.com/smartdevicelink/sdl_ios/files/4320745/2020-03-08_10-57-02.3686_-0600-f66ff644537c9aa2d0c57075a620d170f4875867.txt)

**Comment by NicoleYarroch** [comment] 2020-03-19 17:30
I think I have a fix for this issue. I was only able to reproduce once  but the stack trace did not provide any human readable information. 

All the crash logs show that the crash occurs when the IAP Control Session attempts to close the output stream. I believe the issue is that the output stream's run loop was created on the `lifecycle` thread, which means that the `lifecycle` thread owns the stream. The library then closes the output stream from the main thread. Apple's documentation for streams says [You should never attempt to access a scheduled stream from a thread different than the one owning the stream’s run loop](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Streams/Articles/WritingOutputStreams.html). 

The IAP Control Session is only created when connecting to legacy units that don't support the `multisession` protocol. The IAP Data Session opens and closes the streams on the `ioThread`, which explains why we have not seen this crash on head units that support the `multisession` protocol. 

I will create a PR with a fix.

**Comment by NicoleYarroch** [comment] 2020-03-24 18:04
Fixed in PR #1592

**Closed** 2020-04-14 18:55 UTC
Labels: bug, transport-iap
