### ISSUE TITLE
SDLDebugTool should only log messages when built in DEBUG mode

### ISSUE THREAD

**Issue by adein** [smartdevicelink/sdl_ios#293] opened 2015-08-28 13:52 UTC
Currently, the proxy logs a lot of information to the phone console log using SDLDebugTool.  This class doesn't take the build scheme in to account, so the messages will always be written to the console log.  I would expect log messages would only occur when built in DEBUG mode.

**Comment by joeljfischer** [comment] 2015-08-28 14:14
This is a feature of the logging framework I'm working on here and there that I hope will work for the proxy. https://github.com/livio/SuperLogger

The main thing it's still missing is some unit tests and a server extension to replace siphon.

If you want to take a look and let me know your thoughts, it's definitely appreciated to get eyes on it at any point.

**Comment by joeljfischer** [comment] 2016-01-25 20:08
Duplicate of #74

**Closed by joeljfischer** 2016-01-25 20:08 UTC
Labels: proposal
