### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException NSNull count

### ISSUE THREAD

**Issue by ashwink11** [smartdevicelink/sdl_ios#1174] opened 2019-03-05 10:47 UTC
### Bug Report
Fatal Exception: NSInvalidArgumentException NSNull count

##### Reproduction Steps
Crash report received from released version of App. 

##### Expected Behavior
App should not crash

##### OS & Version Information
* OS Version: 12.1.4 (16D57)
* Device: iPhone 6
* SDL iOS Version: 6.1.2

##### Test Case, Sample Code, and / or Example App
[issue_686_crash.txt](https://github.com/smartdevicelink/sdl_ios/files/2930573/issue_686_crash.txt)

**Comment by joeljfischer** [comment] 2019-03-15 18:35
Duplicate of #1159 / #1153

**Closed by joeljfischer** 2019-03-15 18:35 UTC
Labels: bug
