### ISSUE TITLE
MainField4 in not displayed on Sync 3

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_ios#1105] opened 2018-10-11 14:51 UTC
### Bug Report
mainField4 is not displayed on Sync 3 when the developer doesn't send any `SetDisplayLayout` and set the app type to `DEFAULT`. 

##### Reproduction Steps
- Make sure that no SetDisplayLayout is sent in the app
- Set app type to DEFAULT
- Set the 4 text fields using ScreenManager

##### Expected Behavior
- All mainFields should be displayed 

##### Observed Behavior
- Only mainField1, mainField1, mainField3 are displayed

**Comment by joeljfischer** [comment] 2018-10-11 15:16
Hi @bilal-alsharifi, can you add more information, such as the `textFields` that is retrieved in the `RegisterAppInterfaceResponse.displayCapabilities`? If it returns only mainFields 1-3, then there's a Sync bug and everything in the library is working as intended.

**Comment by bilal-alsharifi** [comment] 2018-10-11 15:37
Hi @joeljfischer. Sure, it returns mainFields 1-4 in `RegisterAppInterfaceResponse.displayCapabilities` but in reality, it cannot display mainField4 in that case. It is a Sync3 bug, not an iOS bug for sure. Sync3 should return only mainFields 1-3 in `RegisterAppInterfaceResponse.displayCapabilities`. But I thought we can patch it and make it work. In Android, we fixed it by sending a Default `SetDisplayLayout` and then we can get the correct display capability from `SetDisplayLayoutResponse`

**Comment by bilal-alsharifi** [comment] 2018-10-11 18:36
We are always sending the `SetDisplayLayout` request in the `ScreenManager` so the developer doesn't have to do it. And as you said we delay transitioning screen manager to READY until the `SetDisplayLayoutResponse` is received. But we don't wait until we are in HMI FULL.

**Comment by joeljfischer** [comment] 2018-10-11 18:47
@bilal-alsharifi The iOS and Android libraries should be in alignment on this, and I don't know that the iOS library (1) can make this change due to it modifying behavior, (2) should make this change as it's pretty dangerous to be sending `SetDisplayLayout` when not in HMI FULL. HMI NONE is heavily restricted on the kinds and number of RPCs that can be sent from that state. Also, this is a fairly significant change to make for a fairly minor HMI bug in an OEM implementation. What if it changes the first template developers expect to be in, for example? How does it affect media and navigation apps? There are many variables here, and I would urge us to discuss it before the change is implemented in Android.

**Comment by joeljfischer** [comment] 2020-01-13 15:35
Closing as a minor Sync issue that can't be fixed well from the app library side.

**Closed by joeljfischer** 2020-01-13 15:35 UTC
Labels: bug
