### ISSUE TITLE
Cache delete daily request from Apple causes apps to disappear from SYNC

### ISSUE THREAD

**Issue by jamesLapinski** [smartdevicelink/sdl_ios#1210] opened 2019-04-01 16:37 UTC
### Bug Report
When leaving your phone off the charger overnight and plugging into SYNC the next morning, a cache delete daily request from Apple kills the apps and causes them to disappear from the head unit. We believe the cache delete daily request is received ~10 minutes after plugging into a power source once a day, this will typically occur when a user plugs their phone in overnight. 

##### Reproduction Steps
1. Leave your device on overnight and do not connect it to a power source.
2. In the morning, connect to the head unit and verify that your apps are connected. 
3. Observe screen for 10-15 minutes.

##### Expected Behavior
Apps stay connected to SYNC system.

##### Observed Behavior
~10 minutes later, multiple (if not all) apps will disappear from the SYNC screen.

##### OS & Version Information
* iOS Version: First observed on 12.0
* SDL iOS Version: n/a, observed on multiple versions.
* Testing Against: Ford SYNC TDK

##### Current Solution
In an effort to keep the app alive on the screen, we have added an innocuous RPC request that will fire off every 5 seconds after the app is backgrounded on the phone for a certain amount of time. The RPC we are currently sending is ListFiles. 

In the limited amount of testing that we have done, the earlier you start to send this RPC, the more likely the app is going to survive. We are looking for a more optimized, in-library solution to this issue.

Testing update: Waited for 30 seconds in background to begin sending RPC messages, app still disappeared. It is possible that a part of the cache delete daily request begins almost immediately after connecting to a power source.

**Comment by joeljfischer** [comment] 2020-01-21 18:52
Is this still an issue? Is there a ticket with apple that can be referenced?

**Comment by E-SAITO-TMC** [comment] 2020-05-13 02:31
@joeljfischer -san, We were able to reproduce this issue with SDL iOS v6.5.0. This is a medium priority issue for Toyota. Is it possible to include this in the next release plan?

**Comment by joeljfischer** [comment] 2020-05-13 12:53
Hi @E-SAITO-TMC, I'm surprised that you can reproduce it. Could you provide the OS version and reproduction steps that you used? I believe that the original authors (Ford) said that they could not. Additionally, I believe that it was determined that this is an iOS issue, not an issue with the library. @stefanek22 @mrapitis can you please confirm if we can close this issue?

**Comment by E-SAITO-TMC** [comment] 2020-05-14 06:09
@joeljfischer -san, We have tested 2 times and have reproduced 2 times. Here are the steps:

**Reproduction Steps**
1, Leave your device on overnight and do not connect it to a power source.
2, In the morning, Connect HS device to HU over USB.
3, Observe screen for 10-15 minutes."

**Observed Behavior**
After step2, All app icon brighten on HU AppList screen,
After step3, All app icon grayed out on HU AppList screen

**Version Information**
SDL Core:6.0.1
Proxy:6.5.0

**Logs**
[1210.zip](https://github.com/smartdevicelink/sdl_ios/files/4626346/1210.zip)

**Comment by joeljfischer** [comment] 2020-05-18 18:38
Thank you @E-SAITO-TMC, can you add information about the iOS version of the phone you were testing with and the HMI you were testing with? As I noted, I believe this is out of SDL control and is an issue that needs to be brought to Apple if it's still present in the latest versions of iOS (13.5.0 beta).

**Comment by E-SAITO-TMC** [comment] 2020-05-25 09:23
@joeljfischer -san,
The reproduced device and iOS version are as follows.
・ IPhone5s (IOS：12.4.4)

It could not be reproduced with the following mobile.
・ IPhone8 (IOS：13.3.1)
・ IPhone11 Pro (IOS：13.2.3)

And we use an HMI that does not use Open Source Software such as Generic HMI.

**Comment by joeljfischer** [comment] 2020-05-26 12:50
@E-SAITO-TMC, based on your testing, would you agree that the issue is an iOS 12 issue that has since been fixed by Apple? If so, I think we can close this issue.

**Comment by E-SAITO-TMC** [comment] 2020-06-05 02:12
@joeljfischer -san. We suspect it's an iOS issue. We could not reproduce it on iOS13. But we have not contacted Apple, and  do not know the cause. Therefore, we cannot determine whether the issue has been fixed.

**Comment by joeljfischer** [comment] 2020-06-05 12:40
Okay. I'm going to close this issue until such a time that someone can provide clear evidence that (1) this is an SDL issue and not an Apple issue, or (2) workaround steps for iOS 12 devices. Feel free to comment and I will reopen the issue for those cases.

**Closed by joeljfischer** 2020-06-05 12:40 UTC
Labels: bug, transport-iap
