### ISSUE TITLE
SDL Crash after SDLIAPSession sdl_accessoryEventLoop

### ISSUE THREAD

**Issue by rosscintelematics** [smartdevicelink/sdl_ios#1178] opened 2019-03-07 23:34 UTC
### Bug Report
App crashes several lines after `[SDLIAPSession sdl_accessoryEventLoop] + 164`. There isn't a whole lot more information on this other than it was observed approximately seven times over one day before being rolled back. I have attached an example crash report. Raising this for tracking purposes, fully aware that more information would be needed to properly investigate.

[2119_crash_.txt](https://github.com/smartdevicelink/sdl_ios/files/2943764/2119_crash_.txt)

```#19. Crashed: com.smartdevicelink.iostream
0  libxpc.dylib                   0x1a83b6614 _xpc_api_misuse + 68
1  (Missing)                      0x5fdc01a83b6608 (Missing)
2  (Missing)                      0x163e81a83b6220 (Missing)
3  (Missing)                      0x307e01a83b5a74 (Missing)
4  (Missing)                      0x48c401a839d8fc (Missing)
5  (Missing)                      0x420a81a90fe904 (Missing)
6  (Missing)                      0x1d9881a90fd86c (Missing)
7  (Missing)                      0x4c3a01a934fc90 (Missing)
8  (Missing)                      0x1a6181cc958604 (Missing)
9  (Missing)                      0x623481bfb746c4 (Missing)
10 (Missing)                      0xb70104041f98 (Missing)
11 SmartDeviceLink                0x104041ac4 -[SDLIAPSession sdl_accessoryEventLoop] + 164
12 Foundation                     0x1a90f0fc0 -[NSThread main] + 72
13 (Missing)                      0x31ae81a922dc44 (Missing)
14 (Missing)                      0x4881a8368974 (Missing)
15 (Missing)                      0x177401a83688d0 (Missing)
16 (Missing)                      0x77e381a8370ddc (Missing)
```

##### Reproduction Steps
There are no reproduction steps at this time. Crash was submitted via Crashlytics in production.
##### Expected Behavior
App does not crash.

##### Observed Behavior
App crashes

##### OS & Version Information
* iOS Version: 12.1.4 on iPhone XS Max
* SDL iOS Version: 4.7.5
* Testing Against: Unknown

##### Test Case, Sample Code, and / or Example App
As above, there isn't more information on this other than it happened.

**Comment by joeljfischer** [comment] 2019-03-15 18:42
Unfortunately, this is an older version of SDL, released in 2017. Without more information, there's not much we can do about this issue. We'll continue to watch for it, but we really need more information.

**Comment by justingluck93** [comment] 2019-04-02 17:22
I am unable to reproduce this issue. Since the other issues raised by you #1179 and #1180 require upgrading to newest version of SDL can you see if the issue persists after that update.

**Comment by rosscintelematics** [comment] 2019-04-02 22:08
Thanks @justingluck93, we are in the process of updating now to 6.1.2, as well as bumping XCode 10.1 and incorporating some feedback from Ford.

**Comment by joeljfischer** [comment] 2019-04-12 19:12
Closing for now. If this reappears on v6.1.2 or v6.2.0 (releasing in a few days) then we can reopen

**Closed by joeljfischer** 2019-04-12 19:12 UTC
Labels: bug
