### ISSUE TITLE
Xcode 12 support with Carthage

### ISSUE THREAD

**Issue by mmdumi** [smartdevicelink/sdl_ios#1797] opened 2020-09-26 11:56 UTC
### Bug Report
Version 6.7.0 of sdl ios doesn't compile on latest xcode12 and swift 5.3 tools.

##### Reproduction Steps
Try to install sdl ios with carthage

```
##### Observed Behavior
*** Fetching sdl_ios
*** Checking out sdl_ios at "6.7.0"
*** xcodebuild output can be found in /var/folders/k_/396c2hcj01x1t115_m9kd4vm0000gn/T/carthage-xcodebuild.x5KDHk.log
*** Building scheme "SmartDeviceLinkSwift" in SmartDeviceLink-iOS.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/mmdumi/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/sdl_ios/6.7.0/Build/Intermediates.noindex/ArchiveIntermediates/SmartDeviceLinkSwift/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SmartDeviceLinkSwift.framework/SmartDeviceLinkSwift /Users/mmdumi/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/sdl_ios/6.7.0/Build/Products/Release-iphonesimulator/SmartDeviceLinkSwift.framework/SmartDeviceLinkSwift -output /Users/mmdumi/ios/w3w/app-ios/Carthage/Build/iOS/SmartDeviceLinkSwift.framework/SmartDeviceLinkSwift

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/k_/396c2hcj01x1t115_m9kd4vm0000gn/T/carthage-xcodebuild.x5KDHk.log
```

##### OS & Version Information
* iOS Version: 14
* SDL iOS Version: 6.7.0

**Comment by joeljfischer** [comment] 2020-09-28 12:30
Hi @mmdumi this is a known issue in Carthage. Please see https://github.com/Carthage/Carthage/issues/3019

**Comment by mmdumi** [comment] 2020-09-28 12:49
That carthage issue was solved by using the following script: https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323
I am using that already for other dependencies but sdl_ios still has issues with it. What are your suggestions for this issue?

**Comment by joeljfischer** [comment] 2020-09-28 13:21
I haven't experienced this issue after using the script provided. I can test again and let you know if I can reproduce it.

**Comment by joeljfischer** [comment] 2020-09-28 15:49
I noticed that you're using v6.7.0. Have you tried pointing at the latest develop branch?

**Comment by mmdumi** [comment] 2020-09-28 16:16
Yes, just tried with both develop and master:
```
./carthage-build.sh --platform ios
/tmp/static.xcconfig.WhCnmI
*** Fetching sdl_ios
*** Checking out sdl_ios at "90317e17d408426547b4afed91620bc695a3279c"
*** xcodebuild output can be found in /var/folders/k_/396c2hcj01x1t115_m9kd4vm0000gn/T/carthage-xcodebuild.b4VCHs.log
*** Building scheme "SmartDeviceLinkSwift" in SmartDeviceLink-iOS.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/mmdumi/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/sdl_ios/90317e17d408426547b4afed91620bc695a3279c/Build/Intermediates.noindex/ArchiveIntermediates/SmartDeviceLinkSwift/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SmartDeviceLinkSwift.framework/SmartDeviceLinkSwift /Users/mmdumi/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/sdl_ios/90317e17d408426547b4afed91620bc695a3279c/Build/Products/Release-iphonesimulator/SmartDeviceLinkSwift.framework/SmartDeviceLinkSwift -output /Users/mmdumi/ios/w3w/app-ios/Carthage/Build/iOS/SmartDeviceLinkSwift.framework/SmartDeviceLinkSwift

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/k_/396c2hcj01x1t115_m9kd4vm0000gn/T/carthage-xcodebuild.b4VCHs.log
```

**Comment by joeljfischer** [comment] 2020-10-02 14:29
I've reproduced and spent quite a bit of time on this. I've tried things that worked for other projects, but to no avail. It seems like many other projects are impacted by this and the script doesn't fix it for them either. Nothing in the logs indicates that something failed to compile, but the non-Swift framework never gets built and the Swift framework is built only with on-device types. The project builds successfully in the project itself. 

I think that until Apple or the Carthage team releases a fix, the workaround is to manually pull in the framework and strip it using the script [as described in our guides](https://smartdevicelink.com/en/guides/iOS/getting-started/installation/#manual-installation). I'll keep this issue open until it is resolved and if an easy temporary fix arises, I'll revisit, but until then, this is a wont-fix issue that needs to be fixed by Carthage or Apple.

**Comment by mmdumi** [comment] 2020-10-02 14:32
What I would suggest (a lot of devs will benefit of this) is to provide in the release section a precompiled .xcframework of sdl_ios. The future of frameworks will most probably be xcframeworks and this will provide backwards compatibility and we will not need Carthage / spm / cocoapods.
You have a tutorial of how to build an xcframework here: https://medium.com/@er.mayursharma14/how-to-create-xcframework-855817f854cf

**Comment by joeljfischer** [comment] 2020-10-02 14:39
It's actually something that I'm looking into for easier SPM support because that will probably be more used than Carthage in the future.

**Comment by joeljfischer** [comment] 2020-10-02 14:39
Also, they're not bundled as `.xcframeworks` right now, but we do have a precompiled `.framework` available on our production Github releases.

**Comment by joeljfischer** [comment] 2020-10-02 14:42
Of course, as soon as I say that, I figure out a fix. I got it to compile for me in a test project using this script:

```bash
#!/usr/bin/env bash

# carthage-build.sh
# Usage example: ./carthage-build.sh --platform iOS

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.

CURRENT_XCODE_VERSION=$(xcodebuild -version | grep "Build version" | cut -d' ' -f3)
echo "EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$CURRENT_XCODE_VERSION = arm64 arm64e armv7 armv7s armv6 armv8" >> $xcconfig

echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage build "$@"
```

Usage: `bash carthage-build.sh --cache-builds --platform iOS`

**Comment by theresalech** [comment] 2020-10-06 18:53
@mmdumi, can you please review the fix above and let us know if this works for you, or if you have any additional feedback? Thank you!

**Comment by mmdumi** [comment] 2020-10-07 08:59
The above script worked. Thank you

**Closed** 2022-03-30 13:01 UTC
Labels: bug, distribution
