### ISSUE TITLE
`EAAccessoryDidConnectNotification` often not firing on background reconnects in iOS 11 beta

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_ios#718] opened 2017-08-31 18:19 UTC
### Bug Report
As of iOS 11, we never receive a EAAccessoryDidConnectNotification via the [NSNotificationCenter defaultCenter] (even after invoking [EAAccessoryManager.sharedAccessoryManager registerForLocalNotifications]). This was not the behavior as of iOS 10 and below. 

##### OS & Version Information
* iOS Version: 11
---
Similar behaviors reported in the iOS developer community are [here](http://www.openradar.me/32602130) and [here](https://forums.developer.apple.com/message/252801#252801).

**Comment by tnelso70** [comment] 2017-09-01 13:35
**Problem:**  The EAAccessoryDidConnectNotification does not trigger on iOS 11 when using the HelloSDL application and SDL proxy.  However, when using Relay without the SDL proxy the EAAccessoryDidConnectNotification triggers nearly 100% of the time.

**Reproduction Steps:**

1)  Add a local notification to the HelloSDL and Relay app to notify the user the EAAccessoryDidConnectNotification triggered
2)  With both HelloSDL and Relay installed, plug the phone into the Sync USB.  You should see local notifications for both HelloSDL and Relay on immediate connection.
3)  Repeatedly unplug and plug back in to see the problem.

**Comment by kshala-ford** [comment] 2017-09-01 14:34
[EA test app.zip](https://github.com/smartdevicelink/sdl_ios/files/1270516/EA.test.app.zip)

Attached ZIP file is a very small Swift project without any SDL related code. It just listens for `EA accessory did connect` or `did disconnect` notifications. It uses [NSlogger](https://github.com/fpillet/NSLogger) to transfer logs to the Mac over WiFi.  

Compiling it with Xcode 9 beta 6 on an iPhone 6 Plus with iOS11 beta 9 I see that the notifications are often not coming up when the app is not in foreground. Chance to fail is about 70-80%.

Reproduction steps:

1. Build and run app on an iOS11 iPhone
1. Press Home button to move app to background
1. Attach phone to e.g. SYNC3 TDK and wait e.g. 5 seconds
1. If app did not deliver "Accessory Did Connect" notification to NSLogger select it on the phone and move it to foreground
1. Detach phone and wait e.g. 5 seconds

Repeat Steps (except first)

Observed behaviour:
- in Step 3 70-80% of the time app does not deliver notification
- In Step 4 app now sends notification

Expected behaviour:
- In Step 3 100% of the time the app should deliver the notification

Comment:
- Observed behaviour cannot be reproduced with iOS 10.3
- As app delivers notification once it moved to foreground it looks like the background apps process stays suspended although "EA did connect" notification should be provided.
- Apple guide says that app should be woken up for 10 seconds in order to connect to the accessory. See [App programming guide for iOS](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW53) which says:
> Upon being woken up, the app has around 10 seconds to process the data. Ideally, it should process the data as fast as possible and allow itself to be suspended again. However, if more time is needed, the app can use the beginBackgroundTaskWithExpirationHandler: method to request additional time; it should do so only when absolutely necessary, though.

**Comment by kshala-ford** [comment] 2017-09-07 14:47
Testing further I noticed a difference on the relay app as it is listening to "battery status change" notifications in addition to "accessory did connect" notifictions. 

With the battery notification the relay app receives the notification >95% of the time. This conforms the observations we all made. Just tried the relay app without listening for battery notifications. Now it's failing as many times as the other apps on iOS11...

I'm assuming iOS11 is resuming suspended background apps if they listen to battery status changes but it lacks of doing so for EA did connect notifications.

**Comment by kshala-ford** [comment] 2017-09-08 09:12
Not sure if it's helpful or relevant to the bug but I was able to increase connction success rate even further (20 of 20 times) by starting a background task on battery notification. The background task starts if battery is charging (so only if the iPhone is attached over USB) and would end either if it expires, after 10 seconds or after the manager is ready (proxy is connected etc.). Without a background task I see the app rarely not getting connected or the app icon not appearing. Once the app is brought to foreground on the phone the app immediately connects and the app icon appears. This makes me think the app gets suspended in the middle of the connection procedure.

See code below:

```objc
@property (nonatomic) UIBackgroundTaskIdentifier backgroundTask;

- (void)batteryStateChanged:(NSNotification *)notification {
  if (UIDevice.currentDevice.batteryState == UIDeviceBatteryStateCharging) {
    self.backgroundTask = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:^{
      if (self.backgroundTask != UIBackgroundTaskInvalid) {
        [[UIApplication sharedApplication] endBackgroundTask:self.backgroundTask];
        self.backgroundTask = UIBackgroundTaskInvalid;
      }
    }];
        
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(10.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
      if (self.backgroundTask != UIBackgroundTaskInvalid) {
        [[UIApplication sharedApplication] endBackgroundTask:self.backgroundTask];
        self.backgroundTask = UIBackgroundTaskInvalid;
      }
    });
  }
}

- (void)start {
  [self.manager startWithReadyHandler:^(BOOL success, NSError * _Nullable error) {
    // regardless if manager is successfuly started. we should end the background task.
    if (self.backgroundTask != UIBackgroundTaskInvalid) {
      [[UIApplication sharedApplication] endBackgroundTask:self.backgroundTask];
      self.backgroundTask = UIBackgroundTaskInvalid;
    }
```

**Comment by NicoleYarroch** [comment] 2017-09-18 13:11
I've tested the app with the iOS 11 GM seed (released 9/11/17), SDL_iOS branch 5.0.0, on iPhone 6+ and have not had any issues with `EAAccessoryDidConnectNotification` not firing.

The reason the app icon is not appearing on SDL Core HMI while the app is in the background is because of bug in the SDL_iOS library. When the app is backgrounded, a background task is created so the app can continue to scan for accessories and complete setup once an accessory is detected. This background task is being prematurely ended, freezing any ongoing tasks. In addition, the background task is never restarted if the app re-enters the background. I have no trouble connecting while the app is in the background when I comment out the code that prematurely ends the background task. 

I am currently working on a fix for the background task issue.

**Comment by kshala-ford** [comment] 2017-09-19 07:40
I can confirm iOS11 GM changes the observed behavior. However the SDL library seems to have issues with the background task (thaks @NicoleYarroch). I would retest again using the public public version as soon as it's released.

Regarding background task we might want to continue that conversation in a separate issue.

**Comment by NicoleYarroch** [comment] 2017-09-19 13:12
I opened issue #740 for the background task

**Comment by joeljfischer** [comment] 2017-09-22 14:27
@NicoleYarroch @kshala-ford Because there's a new issue for that task, it appears this issue can be closed. Any objections?

**Comment by NicoleYarroch** [comment] 2017-09-25 13:06
I have been testing with the iOS 11 release and I have not noticed any issues with the `EAAccessoryDidConnectNotification`. I think we can close this issue.

**Closed** 2017-10-02 13:53 UTC
Labels: bug
