### ISSUE TITLE
Video streaming app using CarWindow API can crash when lock screen is dismissed

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1054] opened 2018-08-16 19:56 UTC
### Bug Report
A video streaming that sets the `CarWindow`'s `rootViewController` to the on-screen view controller (i.e. it is mirroring the screen on the app) can crash when lock screen is dismissed. This is because the `SDLLockScreenPresenter` sets the `appWindow` frame in the `dismiss` method. This can create a race condition where `CarWindow`'s `syncFrame` method's `bounds` is different from its `imageRef` bounds.

At the moment, this only seems to occur when the `rootViewController` is embedded in the tab bar controller.

##### Reproduction Steps
1. Connect a video streaming app using the `CarWindow` API to a TDK that isn't moving (i.e. it should get ad DD_OFF notification). The `rootViewController` should be set to the on-screen view controller.
1. Wait for the lock screen to show and then dismiss.

##### Expected Behavior
It shouldn't crash

##### Observed Behavior
It sometimes crash in the `SDLCarWindow`'s `syncFrame` method because the `bounds` do not match the `imageRef`s bounds.

##### OS & Version Information
* iOS Version: 11.4
* SDL iOS Version: 6.0.1
* Testing Against: TDK

**Comment by joeljfischer** [comment] 2018-11-29 19:08
@NicoleYarroch Do you know if this is still an issue? I believe recent changes have been made.

**Comment by NicoleYarroch** [comment] 2018-11-30 13:35
This bug was reported by a user on the Slack channel. I believe this bug occurs when the set `rootViewController` is embedded in a navigation controller or a tab bar controller. I was never able to reproduce the reported bug.

**Comment by E-SAITO-TMC** [comment] 2020-04-17 08:35
@joeygrover -san @theresalech -san This issue is a top priority for Toyota. I would like know if it will be reproduced in the latest version.

**Comment by joeljfischer** [comment] 2020-04-17 12:50
@E-SAITO-TMC As noted above, Livio has been unable to reproduce this issue at any time. Are you seeing the same issue? If so, please provide reproduction steps and crash logs.

**Comment by E-SAITO-TMC** [comment] 2020-04-21 08:06
@joeljfischer -san Thank you for your reply. I understand. I have not been able to reproduce it too. So, I have no data such as logs, crash reports.

**Comment by joeljfischer** [comment] 2020-04-21 13:39
We will close the issue; it is unreproducible.

**Closed by joeljfischer** 2020-04-21 13:39 UTC
Labels: bug, manager-lockscreen, manager-streaming-video
