### ISSUE TITLE
[SDLIAPDataSession destroySessionWithCompletionHandler:]_block_invoke () crash issue.

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#2008] opened 2021-06-15 07:05 UTC
This bug reference with https://github.com/smartdevicelink/sdl_ios/issues/1892.
it seems bug 1892 not been fixed in SDL v7.1.0, we still got the same crash.

Bug Report
[Summary]
When integrate with our app, it shows 93 devices crash from apple Organizer Crash Report.

Reproduction Steps
Not sure about how to reproduce it.

Expected Behavior
No crash.

Observed Behavior
Show crash report.

OS & Version Information
iOS Version: 13.7-14.6
SDL iOS Version: v7.1.0
Test Case, Sample Code, and / or Example App
#5 (null) in __57-[SDLIAPDataSession destroySessionWithCompletionHandler:]_block_invoke ()
![image](https://user-images.githubusercontent.com/3917323/121988208-7bdc7500-cdcc-11eb-8137-5071757b9781.png)

**Comment by theresalech** [comment] 2021-06-15 14:33
Hi @84798012 , if you're still experiencing issue #1892 when using iOS 7.1.1, please reopen issue #1892. If you could please also provide more details, logs, and/or reproduction steps for what you're currently seeing, that would be helpful for our investigation into the issue. I'll close this issue as a duplicate once you've reopened and provided more information on #1892. Thanks!

**Comment by 84798012** [comment] 2021-06-17 07:56
@theresalech , Hi, there, I can not reopen 1893, because it's not closed by me. Need your help to reopen it. Thanks.

**Comment by theresalech** [comment] 2021-06-17 12:48
Closing as duplicate of #1892.

**Closed by theresalech** 2021-06-17 12:48 UTC
