### ISSUE TITLE
ExternalAccessory:-[EASession _endStreams] crash on our app.

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#2009] opened 2021-06-15 07:08 UTC
This bug reference with https://github.com/smartdevicelink/sdl_ios/issues/1893.
it seems bug 1893 not been fixed in SDL v7.1.0, we still got the same crash.

Bug Report
[Summary]
We recieved crash report from apple organizer.

Reproduction Steps
I'm not sure when cause this crash, but received from apple report.
![image](https://user-images.githubusercontent.com/3917323/122008305-793d4800-cdeb-11eb-97f6-6035f3e434cd.png)

Expected Behavior
No crash.

Observed Behavior
Have crash.

OS & Version Information
iOS Version: 13.5-14.6
SDL iOS Version: 7.1.0

**Comment by theresalech** [comment] 2021-06-15 14:34
Hi @84798012 , if you're still experiencing issue #1893 when using iOS 7.1.1, please reopen issue #1893. If you could please also provide more details, logs, and/or reproduction steps for what you're currently seeing, that would be helpful for our investigation into the issue. I'll close this issue as a duplicate once you've reopened and provided more information on #1893 . Thanks!

**Comment by 84798012** [comment] 2021-06-17 07:56
@theresalech , Hi, there, I can not reopen 1893, because it's not closed by me. Need your help to reopen it. Thanks.

**Comment by theresalech** [comment] 2021-06-17 12:42
Closing as duplicate of #1893.

**Closed by theresalech** 2021-06-17 12:42 UTC
