### ISSUE TITLE
rpcResponseHandlerMap SIGABRT crash in the sdl library

### ISSUE THREAD

**Issue by SunXiaoShan** [smartdevicelink/sdl_ios#1515] opened 2019-12-31 07:36 UTC
I got a crash in the sdl library.
The screen is from Firebase & Cocoapod.
I think the root cause is the variable rpcResponseHandlerMap is nil.
Could you check it again?

![image](https://i.imgur.com/106mxgn.jpg)

![image](https://i.imgur.com/R0jjZrA.png)

##### Reproduction Steps
1. Launch the app
2. Connect with the sdl device
3. Streaming the video

##### OS & Version Information
* iOS Version: 13.3.0
* Mobile: iPhone 11
* SDL iOS Version: 6.4.1

**Comment by NicoleYarroch** [comment] 2020-01-02 21:42
@SunXiaoShan Is it possible to share the full crash report with us? I do not see any obvious bugs that would cause the crash when storing the request handler. I tried setting the `rpcResponseHandlerMap` dictionary to `nil` but that did not cause a crash. Having a `nil` `correlationId` did cause a crash but it is very different from the one you reported.

**Comment by SunXiaoShan** [comment] 2020-01-07 01:14
@NicoleYarroch 
So, I'm so sorry for reply late.
I dont get the feedback notification from github.
Maybe the message is ignored by mail system.
I will try to use 6.3.1 to test it again.
I never saw it before 6.4.1.

Keep monitor.
Thanks,
Phineas Huang

**Comment by NicoleYarroch** [comment] 2020-01-07 13:48
@SunXiaoShan I suspect that the crash is happening because two writes to the `rpcResponseHandlerMap` are being attempted at the same time, however it is difficult to confirm this bug. I will keep an eye out and attach logs to this issue if I can reproduce.

**Comment by SunXiaoShan** [comment] 2020-01-08 01:58
@NicoleYarroch 
Got it, thanks. 
I have no idea for it.
I think one of thing I can do is rollback to sdl 6.3.1 and confirm it again.

**Comment by SunXiaoShan** [comment] 2020-01-14 01:22
@NicoleYarroch 
I have tested it for a week.
It not happens on the sdl 6.3.1

**Comment by NicoleYarroch** [comment] 2020-01-16 13:57
I just had this bug happen on SDL v6.4. I believe the issue is that multiple threads are accessing the `rpcRequestDictionary` at the same time . Since the dictionary is of type `NSMutableDictionary`, it is not thread safe which can cause `EXC BAD ACCESS` errors.

**Comment by NicoleYarroch** [comment] 2020-02-26 16:20
Fixed in PR #1552.

**Closed by NicoleYarroch** 2020-02-26 16:20 UTC
Labels: bug, manager-lifecycle
