### ISSUE TITLE
Investigate Removing Heartbeat

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#368] opened 2016-03-04 20:19 UTC
### Bug Report
Heartbeat has been nothing but an enormous headache on iOS. It hasn't solved any problems, but seems to have generated several (#341, #333). Furthermore, this seems unnecessary because iOS will tell us if a transport disconnects on iAP or over sockets. Heartbeat does not seem to gain us anything. We need to discuss if its removal will cause any other problems, and any advantages it offers that we are not seeing.

We must also assess any risk, and whether heartbeat gains us anything, on Android. I do not believe we should implement on iOS solely for "feature parity", but if we turn heartbeat off entirely or if we make it optional would depend on what is needed on Android.

I consider this high priority because of the unexpected major issues we are seeing as a result of the heartbeat implementation.

A POC or unit test cases would be welcome.

### Expected Behavior
The issues referenced above do not occur.

### Observed Behavior
The issues referenced above occur.

##### OS & Version Information
* iOS Version: 9.2.1
* SDL iOS Version: 4.0.3
* Testing Against: SDL Core, Ford TDK Gen 3

##### Test Case, Sample Code, and / or Example App
This would be welcome if anyone wishes to provide it.

@Heath-FoMoCo @khburdette @asm09fsu @tpulatha @mrapitis @justinjdickow @JackLivio @joeygrover

**Comment by khburdette** [comment] 2016-03-04 20:51
I can do my best to give the background as to why we needed heartbeat in the first place. The 2 main reasons were multiplexing and AOA.

As far as multiplexing, we can always tell when we lose a full transport (unplug USB or disconnect bluetooth) and we can tell when we lose a full serial connection (RFCOMM or accessory string). When app share a serial connection, for example multiple apps on a single RFCOMM port we can't tell when we lose a single app on that connection, just when we lose the full RFCOMM connection.

For AOA, the entire phone goes into an AOA mode/connection and only 1 app is allowed to connect over it. Unfortunately, when the app dies the phone is still in AOA, so we have no idea whether or not the app is available until we physically unplug the device.

That being said, I don't think 2 iOS app can ever share the same accessory string, so we never have to worry about true multiplexing with iOS devices. In addition to that, the iAP transport throws us a curve ball and takes all the data we send to it, but we have no idea (from the app/proxy side) when that data is actually send, so a heartbeat or heartbeat ACK could take minutes before it's actually sent making it completely useless.

Assuming everything I said was true, I agree that we need to get rid of heartbeat for iOS devices. This becomes a little tricky because SDL doesn't know what kind of device is connected so we need to create some sort of heartbeat negotiation. Also, protocol v3 assumes heartbeat is going to be active so we probably need to rev the protocol as well.

Hope that helps a little.

**Comment by joeljfischer** [comment] 2016-03-07 21:52
From what @joeygrover was saying in chat, it doesn't seem like Heartbeat is necessary for multiplexing even on a single RFCOMM port, unless I'm mistaken.

From what @Heath-FoMoCo was saying, it looks like Core doesn't actually look for heartbeat or send it, it's all library initiated, so if we don't send it, Core won't ever do anything about it, meaning that we can remove it even now.

**Comment by khburdette** [comment] 2016-03-08 14:14
Multiplexing happens at the SDL protocol level, so without a mechanism at that point (or higher), I don't think it could possibly tell. What's the mechanism that's detecting this?

That's just not true ... there aren't many cases where core is the one responsible for sending the heartbeat, but when it's supposed to, it definitely does.

**Comment by joeljfischer** [comment] 2016-03-08 14:24
Paging @joeygrover on the first one, since I don't want to copy-pasta his words out of private chat.

The second one was mentioned by @Heath-FoMoCo, but @justinjdickow or @JackLivio can possibly also speak to it. Can you enumerate the times when core is responsible for sending heartbeat? We've never seen it occur.

**Comment by justinjdickow** [comment] 2016-03-08 14:52
From what I can find internally on the requirements that were implemented in Core for heartbeat:

>both core and mobile need to have the logic to send a heartbeat and respond to a heartbeat.

and

```

Pre-conditions:
app connects over protocol v3 to SDL
Steps:
app -> SDL: Heartbeat_request
SDL -> app: Heartbeat_ACK
SDL starts Heartbeat timeout (<Heartbeat> param in .ini file)
app doesn`t send Heartbeat_request, RPC or data streaming
Expected:
SDL -> app: Heartbeat_request
SDL starts Heartbeat timeout (<Heartbeat> param in .ini file)
```

So it would happen with protocol v3 or higher, if the app doesn't send a heartbeat first within the timeout specified in Core. Whether that logic is implemented in SDL Core, I have not confirmed yet

**Comment by joeljfischer** [comment] 2016-03-08 15:22
So, basically, it sounds like even though heartbeat confers no benefit and causes numerous issues, at least on iOS and maybe Android, we can't actually remove it. :cry:

**Comment by asm09fsu** [comment] 2016-03-08 16:17
Sounds like we need to change the spec then.

**Comment by joeljfischer** [comment] 2016-03-08 16:19
@asm09fsu The problem is that it's already in production, so, from what I understand, we can't retroactively change it. We could change it in future protocol versions (and should), but that doesn't actually solve our problem.

**Comment by khburdette** [comment] 2016-03-08 18:02
I want to attempt to throw out some proposals ... 

I think we could mostly kinda deprecate v3 protocol from the mobile side. We can't completely erase it from existence because it's already out there and in production. Almost all of the current SDL enabled apps won't ever need to use v3. Basically we only let apps that need to send large amounts of data (via put file, system request, or whatever) and mobile nav apps use v3. For all other apps, during the protocol version negotiation they will default to v2 when the head unit only supports up to v3, or they use something higher than v3.

Thoughts?

**Comment by joeygrover** [comment] 2016-03-08 19:42
What's the value in doing that? We have to ensure that v3 of the protocol works and works well on both sides for those special cases. So why not just let all apps use v3?

**Comment by asm09fsu** [comment] 2016-03-18 16:02
@joeljfischer can we close this now?

**Comment by joeljfischer** [comment] 2016-03-18 16:15
It will be closed automatically when it's merged to master

**Closed** 2016-03-30 16:45 UTC
Labels: bug, high priority
